# -*- coding: utf-8 -*-
"""Calculo_IMC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJ6ZcWLjuJT2i1GlL4ANQGkASWzNs59U
"""

import pandas as pd
import numpy as np

# Importação dos Dados
df = pd.read_csv('dataset.CSV', ';')

pd.set_option('display.max_rows', df.shape[0]+1)

# Remova as linhas em branco nos dados, se houver
df.dropna(inplace=True)

df

# Função que muda todo o texto para maiúsculas
def upperlize(df, desired_cols):
    result = df.copy()
    for feature_name in desired_cols:
        result[feature_name] = [entry.upper() for entry in df[feature_name]]
    return result

#  Função que converte os valores da coluna Peso (kg) e Altura (m) para float
def floatlize(df, desired_cols):
    result = df.copy()
    for feature_name in desired_cols:
        result[feature_name] = pd.to_numeric(df[feature_name].str.replace(',','.'))
    return result

#  Função que retira os espaços extras das colunas Primeiro Nome e Sobrenomes
def striplize(df, desired_cols):
    result = df.copy()
    for feature_name in desired_cols:
        result[feature_name] = df[feature_name].str.split().str.join(' ').str.strip()
    return result

# Muda todo o texto para maiúsculas
df = upperlize(df,['Primeiro Nome','Sobrenomes'])

# Convertendo os valores da coluna Peso (kg) e Altura (m) para float
df = floatlize(df,['Peso (kg)','Altura (m)'])

# Retira os espaços extras das colunas Primeiro Nome e Sobrenomes
df = striplize(df,['Primeiro Nome','Sobrenomes'])

# Calcula o IMC
calc_IMC = round((df['Peso (kg)']) / (df['Altura (m)']**2), 2)

# Lista os resultados do IMC
List_calc_IMC = list(map(str, calc_IMC))

# Substitui os '.' por ','
List_calc_IMC = [sub.replace('.', ',') for sub in List_calc_IMC]

# Concatena as Strings para gerar a Saida esperada
Saida = df['Primeiro Nome']+ ' ' + df['Sobrenomes'] + ' ' + List_calc_IMC

Saida

# Saida
for val in Saida:
    print(val)

#Salvar Saida em Arquivo .txt
with open("PauloHenriqueMirandaSa.txt", "w") as output:
    for val in Saida:
      output.write(str(val) + '\n')